name: .NET-CORE6.0-UnitTest-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: appservice-manjeet
  AZURE_WEBAPP_PACKAGE_PATH: "app"

jobs:
  use-action:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        # Importing common steps from the other repository
        - name: Import Common Steps
          uses: actions/checkout@v3
          with:
            repository: manjeet-yadav123/Pipeline-Common
            path: stages/steps/.net-ci-steps.yml

