name: CD Steps

on:
  workflow_call:
    inputs:
      deployment-environment:
jobs:
  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app
