name: .NET Core CI Steps

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Setup .NET Core SDK
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '3.1.x' # Specify the version of .NET Core you want to use

    # - name: Restore dependencies
    #   run: dotnet restore '**/*.sln'

    # - name: Build
    #   run: dotnet build '**/*.sln' --configuration Release --no-restore
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: AspNetCoreTests
    - name: Build
      run: dotnet build --configuration Release
      working-directory: AspNetCoreTests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: 'AspNetCoreTests'
      continue-on-error: true

    - name: dotnet publish 
      run: dotnet publish AspNetCoreTests/AspNetCoreTests.Web/*.csproj -c Release -o website

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: website/**
        if-no-files-found: error
