on:
  push:
    branches: [ "main" ]
  # Add more triggers as needed

jobs:
  deploy_to_qa:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app
