# on:
#   push:
#     branches: [ "main" ]
#   # Add more triggers as needed
on:
  workflow_call:
jobs:
  deploy_to_qa:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app
