deploy:
  uses: manjeet-yadav123/Pipeline-Common/.github/workflows/.net.cd-steps.yml@main

on:
  push:
    branches: [ "main" ]
  # Add more triggers as needed

jobs:
  deploy_to_qa:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app
