name: .NET Core CI Steps

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # Specify the version of .NET Core you want to use

    - name: Restore dependencies
      run: dotnet restore '**/*.sln'

    - name: Build
      run: dotnet build '**/*.sln' --configuration Release --no-restore
