# Repo2: .github/workflows/abc.yml

name: ABC Action

on:
  push:
    branches:
      - main

jobs:
  abc_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Step 1 of the ABC action"

      # Add more steps as needed
