name: .NET Core CI Steps

on:
  workflow_call:
    inputs:
      solution_path:
        description: "Path to the .sln file"
        required: true
      configuration:
        description: "Build configuration (e.g., Debug, Release)"
        required: false
        default: "Release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # Specify the version of .NET Core you want to use

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution_path }}

    - name: Build
      run: dotnet build ${{ inputs.solution_path }} --configuration ${{ inputs.configuration }} --no-restore

    - name: Test
      run: dotnet test ${{ inputs.solution_path }} --no-restore --verbosity normal
